// frontend/src/views/Dreams/CreateDream.vue
<template>
  <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
    <div class="px-4 py-6 sm:px-0">
      <div class="flex flex-col">
        <button
          @click.prevent="addPost"
          class="
            ml-auto
            bg-blue-500
            hover:bg-blue-700
            text-white
            font-bold
            p-3
            rounded-full
          "
        >
          Submit
        </button>
        <input
          v-model="postContent"
          type="text"
          class="
            rounded
            border-2 border-gray-600
            w-3/4
            my-4
            h-48
            m-auto
            max-w-7xl
            p-2
          "
        />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "CreateDream",
  data() {
    return {
      postContent: null,
    };
  },

  methods: {
    addPost() {
      if (this.postContent) {
        this.$store.dispatch("dreams/saveDream", this.postContent);

        this.$router.push("/dreams/overview");
      }
    },
  },
};
</script>

// frontend-react/src/screens/dreams/CreateDream.tsx
import { FC } from "react";

const CreateDream: FC = () => {
  return (
    <div className="max-w-7xl mx-auto">
      <div className="px-4 py-6">
        <div className="flex flex-col justify-center">
          <input
            v-model="postContent"
            type="text"
            className="
            rounded
            border-2 border-gray-600
            w-3/4
            my-4
            h-48
            mx-auto
            max-w-7xl
            p-2
          "
          />
          <button
            className="
            w-20
            m-auto
            bg-blue-500
            hover:bg-blue-700
            text-white
            font-bold
            p-2
            rounded
          "
          >
            Submit
          </button>
        </div>
      </div>
    </div>
  );
};

export default CreateDream;
